In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("riders.csv")

In [3]:
df.head()

,rider_id,national_id,phone_number,age,gender,county,sub_location,rider_segment,bike_ownership,bike_age_years,sacco_id,app_platform,months_operating,application_date
0,RDR-00001,32706266,790671858,30,Male,Nairobi,Zimmerman,Hybrid Rider,Owned,5.0,SAC-002,Bolt,62,2024-06-30
1,RDR-00002,28832259,722850800,27,Male,Nairobi,Ngong,Stage Rider,Owned,1.7,SAC-001,NaN,15,2024-06-30
2,RDR-00003,39168878,712895667,35,Male,Nairobi,Zimmerman,App Rider,Owned,7.8,NaN,Bolt,4,2024-06-30
3,RDR-00004,21294238,712197251,31,Male,Nairobi,Kasarani,App Rider,Owned,2.1,NaN,InDriver,70,2024-06-30
4,RDR-00005,34485735,710662275,25,Male,Nairobi,Roysambu,SACCO Member,Hired,4.4,SAC-001,NaN,27,2024-06-30

In [4]:
import os
os.listdir()

['.ipynb_checkpoints',
 'anaconda_projects',
 'apps_clean.csv',
 'app_trip_data.csv',
 'Cleaning.ipynb',
 'credit_applications.csv',
 'Datagenerator.py',
 'featureEngineering.ipynb',
 'featureengineering2.ipynb',
 'featureengineeringreal.ipynb',
 'features.csv',
 'feature_cols.json',
 'loans_clean.csv',
 'loan_history.csv',
 'model_training.ipynb',
 'mpesa_clean.csv',
 'mpesa_transactions.csv',
 'requirements.txt',
 'riders.csv',
 'riders_clean.csv',
 'sacco_clean.csv',
 'sacco_records.csv',
 'trips_clean.csv',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'venv']

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
riders = pd.read_csv("riders.csv")
riders.head()

,rider_id,national_id,phone_number,age,gender,county,sub_location,rider_segment,bike_ownership,bike_age_years,sacco_id,app_platform,months_operating,application_date
0,RDR-00001,32706266,790671858,30,Male,Nairobi,Zimmerman,Hybrid Rider,Owned,5.0,SAC-002,Bolt,62,2024-06-30
1,RDR-00002,28832259,722850800,27,Male,Nairobi,Ngong,Stage Rider,Owned,1.7,SAC-001,NaN,15,2024-06-30
2,RDR-00003,39168878,712895667,35,Male,Nairobi,Zimmerman,App Rider,Owned,7.8,NaN,Bolt,4,2024-06-30
3,RDR-00004,21294238,712197251,31,Male,Nairobi,Kasarani,App Rider,Owned,2.1,NaN,InDriver,70,2024-06-30
4,RDR-00005,34485735,710662275,25,Male,Nairobi,Roysambu,SACCO Member,Hired,4.4,SAC-001,NaN,27,2024-06-30

In [7]:
mpesa = pd.read_csv("mpesa_transactions.csv")
mpesa.head()

,transaction_id,rider_id,transaction_date,transaction_type,amount,direction,counterparty_name,counterparty_type,channel,running_balance,month,week_number
0,TXN-RDR-00001-00001,RDR-00001,2024-04-01 07:28:00,Receive Money,676.15,IN,App Payout,INCOME_IN,P2P,3382.55,4,14
1,TXN-RDR-00001-00002,RDR-00001,2024-04-01 06:05:00,Pay Bill,281.43,OUT,Rubis Energy,FUEL,Paybill,3101.12,4,14
2,TXN-RDR-00001-00003,RDR-00001,2024-04-01 10:00:00,Pay Bill,713.47,OUT,Eastside Riders SACCO,SACCO_CONTRIB,Paybill,2387.65,4,14
3,TXN-RDR-00001-00004,RDR-00001,2024-04-01 08:00:00,Airtime Purchase,50.00,OUT,Safaricom Airtime,AIRTIME,Airtime,2337.65,4,14
4,TXN-RDR-00001-00005,RDR-00001,2024-04-02 07:42:00,Receive Money,751.28,IN,App Payout,INCOME_IN,Cash In,3088.93,4,14

In [8]:
loans = pd.read_csv("loan_history.csv")
loans.head()

,loan_id,rider_id,lender_name,lender_type,loan_amount,loan_purpose,disbursement_date,due_date,completion_date,days_early_late,default_flag,restructured_flag,outstanding_balance,repayment_frequency
0,LN-000001,RDR-00003,Tala Kenya,Digital,4496.31,Bike Repair,2023-05-07,2023-07-06,2023-07-15,9,False,False,0.00,Weekly
1,LN-000002,RDR-00003,Branch International,Digital,4191.17,Business Expansion,2023-05-07,2023-07-06,2023-07-04,-2,False,False,0.00,Monthly
2,LN-000003,RDR-00003,Juhudi Kilimo,MFI,27601.41,Bike Upgrade,2023-05-07,2023-08-05,2023-09-06,32,False,False,0.00,Weekly
3,LN-000004,RDR-00003,Musoni Kenya,MFI,61678.14,Bike Repair,2023-08-05,2024-08-04,NaN,0,False,False,24751.76,Monthly
4,LN-000005,RDR-00005,Juhudi Kilimo,MFI,19032.38,Emergency Medical,2023-04-07,2024-04-06,2024-04-02,-4,False,False,0.00,Daily

In [9]:
sacco   = pd.read_csv("sacco_records.csv")

In [10]:
trips   = pd.read_csv("app_trip_data.csv")

In [11]:
apps    = pd.read_csv("credit_applications.csv")

In [12]:
for name, df in [("riders", riders), ("mpesa", mpesa),
                  ("sacco", sacco), ("loans", loans),
                  ("trips", trips), ("apps", apps)]:
    print(f"  {name:8s}: {df.shape[0]:>7,} rows  x  {df.shape[1]:>2} columns")

  riders  :   1,000 rows  x  14 columns
  mpesa   : 203,386 rows  x  12 columns
  sacco   :   5,227 rows  x  14 columns
  loans   :   1,390 rows  x  14 columns
  trips   :  22,828 rows  x  10 columns
  apps    :   1,000 rows  x  15 columns

In [13]:
sacco.head()

,record_id,rider_id,sacco_id,month_year,months_as_member,monthly_contribution,contribution_made,contribution_on_time,days_late,cumulative_savings,shares_owned,active_loan_balance,loan_repayment_status,guarantor_count
0,SAC-RDR-00001-202301,RDR-00001,SAC-002,2023-01,1,1591.67,True,True,0,1591.67,1,0.0,Clean,1
1,SAC-RDR-00001-202302,RDR-00001,SAC-002,2023-02,2,1591.67,True,True,0,3183.33,1,0.0,Clean,0
2,SAC-RDR-00001-202303,RDR-00001,SAC-002,2023-03,3,1591.67,True,True,0,4775.00,1,0.0,Clean,0
3,SAC-RDR-00001-202304,RDR-00001,SAC-002,2023-04,4,1591.67,True,True,0,6366.66,1,0.0,Clean,3
4,SAC-RDR-00001-202305,RDR-00001,SAC-002,2023-05,5,1591.67,False,True,0,6366.66,1,0.0,Clean,1

In [14]:
trips.head()

,trip_record_id,rider_id,week_start_date,total_trips,active_days,gross_earnings_week,platform_rating,cancellation_rate,peak_hour_trips,longest_inactive_streak
0,TR-RDR-00001-W52,RDR-00001,2023-07-02,45,6,7879.83,4.3,0.099,17,0
1,TR-RDR-00001-W51,RDR-00001,2023-07-09,56,6,8916.24,4.4,0.049,22,0
2,TR-RDR-00001-W50,RDR-00001,2023-07-16,42,5,5699.78,4.4,0.042,15,1
3,TR-RDR-00001-W49,RDR-00001,2023-07-23,40,5,4893.77,4.3,0.065,19,1
4,TR-RDR-00001-W48,RDR-00001,2023-07-30,47,7,5853.08,4.4,0.102,18,0

In [15]:
apps.head()

,application_id,rider_id,application_date,requested_amount,requested_term_days,loan_purpose,score_date,final_score,risk_category,pd_score,recommended_amount,recommended_term_days,decision,actual_default,risk_score_debug
0,APP-2024-RDR-00001,RDR-00001,2024-06-30,10000,90,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,6.36
1,APP-2024-RDR-00002,RDR-00002,2024-06-30,15000,60,Bike Repair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,23.69
2,APP-2024-RDR-00003,RDR-00003,2024-06-30,20000,180,Working Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,10.00
3,APP-2024-RDR-00004,RDR-00004,2024-06-30,20000,120,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,26.25
4,APP-2024-RDR-00005,RDR-00005,2024-06-30,50000,30,Emergency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1.00

In [16]:
mpesa["counterparty_type"].value_counts()

counterparty_type
INCOME_IN        82728
FUEL             72853
AIRTIME          31535
SACCO_CONTRIB    13000
FAMILY_SEND       2612
DIGITAL_LOAN       658
Name: count, dtype: int64

In [17]:
sacco["contribution_on_time"].value_counts()

contribution_on_time
True     4607
False     620
Name: count, dtype: int64

In [18]:
def table_health_check(df, name):
    print(f"\n{'='*50}")
    print(f"  {name.upper()} — HEALTH CHECK")
    print(f"{'='*50}")
    print(f"  Shape: {df.shape[0]} rows x {df.shape[1]} columns")
    
    # Missing values
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) == 0:
        print("  ✅ No missing values")
    else:
        print(f"  ⚠️  Missing values found:")
        for col, count in missing.items():
            pct = count / len(df) * 100
            print(f"     {col:<35} {count:>5} missing ({pct:.1f}%)")
    
    # Data types
    print(f"\n  Column data types:")
    for col, dtype in df.dtypes.items():
        print(f"     {col:<35} {str(dtype)}")

# Run health check on all tables
table_health_check(riders, "riders")
table_health_check(mpesa,  "mpesa transactions")
table_health_check(sacco,  "sacco records")
table_health_check(loans,  "loan history")
table_health_check(trips,  "app trip data")
table_health_check(apps,   "credit applications")

==================================================
  RIDERS — HEALTH CHECK
==================================================
  Shape: 1000 rows x 14 columns
  ⚠️  Missing values found:
     sacco_id                              631 missing (63.1%)
     app_platform                          561 missing (56.1%)

  Column data types:
     rider_id                            object
     national_id                         int64
     phone_number                        int64
     age                                 int64
     gender                              object
     county                              object
     sub_location                        object
     rider_segment                       object
     bike_ownership                      object
     bike_age_years                      float64
     sacco_id                            object
     app_platform                        object
     months_operating                    int64
     application_date                    object

==================================================
  MPESA TRANSACTIONS — HEALTH CHECK
==================================================
  Shape: 203386 rows x 12 columns
  ✅ No missing values

  Column data types:
     transaction_id                      object
     rider_id                            object
     transaction_date                    object
     transaction_type                    object
     amount                              float64
     direction                           object
     counterparty_name                   object
     counterparty_type                   object
     channel                             object
     running_balance                     float64
     month                               int64
     week_number                         int64

==================================================
  SACCO RECORDS — HEALTH CHECK
==================================================
  Shape: 5227 rows x 14 columns
  ✅ No missing values

  Column data types:
     record_id                           object
     rider_id                            object
     sacco_id                            object
     month_year                          object
     months_as_member                    int64
     monthly_contribution                float64
     contribution_made                   bool
     contribution_on_time                bool
     days_late                           int64
     cumulative_savings                  float64
     shares_owned                        int64
     active_loan_balance                 float64
     loan_repayment_status               object
     guarantor_count                     int64

==================================================
  LOAN HISTORY — HEALTH CHECK
==================================================
  Shape: 1390 rows x 14 columns
  ⚠️  Missing values found:
     completion_date                       315 missing (22.7%)

  Column data types:
     loan_id                             object
     rider_id                            object
     lender_name                         object
     lender_type                         object
     loan_amount                         float64
     loan_purpose                        object
     disbursement_date                   object
     due_date                            object
     completion_date                     object
     days_early_late                     int64
     default_flag                        bool
     restructured_flag                   bool
     outstanding_balance                 float64
     repayment_frequency                 object

==================================================
  APP TRIP DATA — HEALTH CHECK
==================================================
  Shape: 22828 rows x 10 columns
  ✅ No missing values

  Column data types:
     trip_record_id                      object
     rider_id                            object
     week_start_date                     object
     total_trips                         int64
     active_days                         int64
     gross_earnings_week                 float64
     platform_rating                     float64
     cancellation_rate                   float64
     peak_hour_trips                     int64
     longest_inactive_streak             int64

==================================================
  CREDIT APPLICATIONS — HEALTH CHECK
==================================================
  Shape: 1000 rows x 15 columns
  ⚠️  Missing values found:
     score_date                           1000 missing (100.0%)
     final_score                          1000 missing (100.0%)
     risk_category                        1000 missing (100.0%)
     pd_score                             1000 missing (100.0%)
     recommended_amount                   1000 missing (100.0%)
     recommended_term_days                1000 missing (100.0%)
     decision                             1000 missing (100.0%)

  Column data types:
     application_id                      object
     rider_id                            object
     application_date                    object
     requested_amount                    int64
     requested_term_days                 int64
     loan_purpose                        object
     score_date                          float64
     final_score                         float64
     risk_category                       float64
     pd_score                            float64
     recommended_amount                  float64
     recommended_term_days               float64
     decision                            float64
     actual_default                      bool
     risk_score_debug                    float64

In [19]:
mpesa["transaction_date"] = pd.to_datetime(mpesa["transaction_date"])

In [20]:
riders["application_date"] = pd.to_datetime(riders["application_date"])

In [21]:
sacco["month_year"] = pd.to_datetime(sacco["month_year"])

In [22]:
trips["week_start_date"] = pd.to_datetime(trips["week_start_date"])

In [23]:
riders["national_id"] = riders["national_id"].astype(object)

In [24]:
riders["phone_number"] = riders["phone_number"].astype(object)

In [25]:
riders.dtypes

rider_id                    object
national_id                 object
phone_number                object
age                          int64
gender                      object
county                      object
sub_location                object
rider_segment               object
bike_ownership              object
bike_age_years             float64
sacco_id                    object
app_platform                object
months_operating             int64
application_date    datetime64[ns]
dtype: object

In [26]:
riders["sacco_id"].value_counts()

sacco_id
SAC-002    56
SAC-004    52
SAC-006    49
SAC-001    47
SAC-008    45
SAC-005    42
SAC-003    39
SAC-007    39
Name: count, dtype: int64

In [27]:
riders["bike_ownership"].value_counts()

bike_ownership
Hired    558
Owned    442
Name: count, dtype: int64

In [28]:
riders["bike_owned"] = (riders["bike_ownership"] == "Owned").astype(int)

In [29]:
riders["has_sacco"] = riders["sacco_id"].notna().astype(int)

In [30]:
riders["has_app"] = riders["app_platform"].notna().astype(int)

In [31]:
segment_risk_map = {
    "SACCO Member":  1,
    "Owner Rider":   2,
    "App Rider":     3,
    "Hybrid Rider":  4,
    "Stage Rider":   5,
}
riders["segment_risk_score"] = riders["rider_segment"].map(segment_risk_map)

In [32]:
riders.head()

,rider_id,national_id,phone_number,age,gender,county,sub_location,rider_segment,bike_ownership,bike_age_years,sacco_id,app_platform,months_operating,application_date,bike_owned,has_sacco,has_app,segment_risk_score
0,RDR-00001,32706266,790671858,30,Male,Nairobi,Zimmerman,Hybrid Rider,Owned,5.0,SAC-002,Bolt,62,2024-06-30,1,1,1,4
1,RDR-00002,28832259,722850800,27,Male,Nairobi,Ngong,Stage Rider,Owned,1.7,SAC-001,NaN,15,2024-06-30,1,1,0,5
2,RDR-00003,39168878,712895667,35,Male,Nairobi,Zimmerman,App Rider,Owned,7.8,NaN,Bolt,4,2024-06-30,1,0,1,3
3,RDR-00004,21294238,712197251,31,Male,Nairobi,Kasarani,App Rider,Owned,2.1,NaN,InDriver,70,2024-06-30,1,0,1,3
4,RDR-00005,34485735,710662275,25,Male,Nairobi,Roysambu,SACCO Member,Hired,4.4,SAC-001,NaN,27,2024-06-30,0,1,0,1

In [33]:
RIDERS_COLS_TO_DROP = [
    "national_id",      
    "phone_number",      
    "gender",           
    "county",            
    "sub_location",      
    "rider_segment",    
    "bike_ownership",    
    "sacco_id",          
    "app_platform",      
    "application_date",  
]

riders_clean = riders.drop(columns=RIDERS_COLS_TO_DROP)

In [34]:
riders_clean.head()

,rider_id,age,bike_age_years,months_operating,bike_owned,has_sacco,has_app,segment_risk_score
0,RDR-00001,30,5.0,62,1,1,1,4
1,RDR-00002,27,1.7,15,1,1,0,5
2,RDR-00003,35,7.8,4,1,0,1,3
3,RDR-00004,31,2.1,70,1,0,1,3
4,RDR-00005,25,4.4,27,0,1,0,1

In [35]:
mpesa["transaction_date"] = pd.to_datetime(mpesa["transaction_date"])

In [36]:
mpesa.head()

,transaction_id,rider_id,transaction_date,transaction_type,amount,direction,counterparty_name,counterparty_type,channel,running_balance,month,week_number
0,TXN-RDR-00001-00001,RDR-00001,2024-04-01 07:28:00,Receive Money,676.15,IN,App Payout,INCOME_IN,P2P,3382.55,4,14
1,TXN-RDR-00001-00002,RDR-00001,2024-04-01 06:05:00,Pay Bill,281.43,OUT,Rubis Energy,FUEL,Paybill,3101.12,4,14
2,TXN-RDR-00001-00003,RDR-00001,2024-04-01 10:00:00,Pay Bill,713.47,OUT,Eastside Riders SACCO,SACCO_CONTRIB,Paybill,2387.65,4,14
3,TXN-RDR-00001-00004,RDR-00001,2024-04-01 08:00:00,Airtime Purchase,50.00,OUT,Safaricom Airtime,AIRTIME,Airtime,2337.65,4,14
4,TXN-RDR-00001-00005,RDR-00001,2024-04-02 07:42:00,Receive Money,751.28,IN,App Payout,INCOME_IN,Cash In,3088.93,4,14

In [37]:
mpesa["txn_date"]       = mpesa["transaction_date"].dt.date
mpesa["txn_month"]      = mpesa["transaction_date"].dt.month
mpesa["txn_day"]        = mpesa["transaction_date"].dt.day
mpesa["txn_weekday"]    = mpesa["transaction_date"].dt.weekday  # 0=Mon, 6=Sun
mpesa["is_weekend"]     = (mpesa["txn_weekday"] >= 5).astype(int)
mpesa["is_end_month"]   = (mpesa["txn_day"] >= 28).astype(int)
mpesa["is_rain_month"]  = mpesa["txn_month"].isin([3, 4, 5, 10, 11]).astype(int)

In [38]:
negative_amounts = (mpesa["amount"] < 0).sum()
print(f"Negative amount rows: {negative_amounts}")

Negative amount rows: 0

In [39]:
print("\nTransaction types in dataset:")
print(mpesa["counterparty_type"].value_counts())

Transaction types in dataset:
counterparty_type
INCOME_IN        82728
FUEL             72853
AIRTIME          31535
SACCO_CONTRIB    13000
FAMILY_SEND       2612
DIGITAL_LOAN       658
Name: count, dtype: int64

In [40]:
mpesa_clean["is_weekend"]    = (mpesa_clean["txn_weekday"] >= 5).astype(int)
mpesa_clean["is_end_month"]  = (mpesa_clean["txn_day"] >= 28).astype(int)
mpesa_clean["is_rain_month"] = mpesa_clean["txn_month"].isin(
    [3, 4, 5, 10, 11]
).astype(int)
mpesa_clean["is_peak_hour"]  = mpesa_clean["txn_hour"].isin(
    [7, 8, 9, 17, 18, 19, 20]   # morning and evening rush hours
).astype(int)

NameError: name 'mpesa_clean' is not defined

In [41]:
MPESA_DROP_COLS = [
    "transaction_id",    
    "transaction_type", 
    "channel",           
    "month",             
    "week_number",      
]

mpesa_clean = mpesa.drop(columns=MPESA_DROP_COLS)

In [42]:
print("SHAPE:", mpesa.shape)
print()
print("COLUMN TYPES:")
print(mpesa.dtypes)
print()
print("MISSING VALUES:")
print(mpesa.isnull().sum())
print()
print("FIRST 5 ROWS:")
display(mpesa.head())
print()
print("UNIQUE TRANSACTION TYPES:")
print(mpesa["counterparty_type"].value_counts())
print()
print("UNIQUE DIRECTIONS:")
print(mpesa["direction"].value_counts())
print()
print("AMOUNT STATS:")
print(mpesa["amount"].describe())
print()
print("RUNNING BALANCE STATS:")
print(mpesa["running_balance"].describe())

SHAPE: (203386, 19)

COLUMN TYPES:
transaction_id               object
rider_id                     object
transaction_date     datetime64[ns]
transaction_type             object
amount                      float64
direction                    object
counterparty_name            object
counterparty_type            object
channel                      object
running_balance             float64
month                         int64
week_number                   int64
txn_date                     object
txn_month                     int32
txn_day                       int32
txn_weekday                   int32
is_weekend                    int64
is_end_month                  int64
is_rain_month                 int64
dtype: object

MISSING VALUES:
transaction_id       0
rider_id             0
transaction_date     0
transaction_type     0
amount               0
direction            0
counterparty_name    0
counterparty_type    0
channel              0
running_balance      0
month                0
week_number          0
txn_date             0
txn_month            0
txn_day              0
txn_weekday          0
is_weekend           0
is_end_month         0
is_rain_month        0
dtype: int64

FIRST 5 ROWS:

,transaction_id,rider_id,transaction_date,transaction_type,amount,direction,counterparty_name,counterparty_type,channel,running_balance,month,week_number,txn_date,txn_month,txn_day,txn_weekday,is_weekend,is_end_month,is_rain_month
0,TXN-RDR-00001-00001,RDR-00001,2024-04-01 07:28:00,Receive Money,676.15,IN,App Payout,INCOME_IN,P2P,3382.55,4,14,2024-04-01,4,1,0,0,0,1
1,TXN-RDR-00001-00002,RDR-00001,2024-04-01 06:05:00,Pay Bill,281.43,OUT,Rubis Energy,FUEL,Paybill,3101.12,4,14,2024-04-01,4,1,0,0,0,1
2,TXN-RDR-00001-00003,RDR-00001,2024-04-01 10:00:00,Pay Bill,713.47,OUT,Eastside Riders SACCO,SACCO_CONTRIB,Paybill,2387.65,4,14,2024-04-01,4,1,0,0,0,1
3,TXN-RDR-00001-00004,RDR-00001,2024-04-01 08:00:00,Airtime Purchase,50.00,OUT,Safaricom Airtime,AIRTIME,Airtime,2337.65,4,14,2024-04-01,4,1,0,0,0,1
4,TXN-RDR-00001-00005,RDR-00001,2024-04-02 07:42:00,Receive Money,751.28,IN,App Payout,INCOME_IN,Cash In,3088.93,4,14,2024-04-02,4,2,1,0,0,1

UNIQUE TRANSACTION TYPES:
counterparty_type
INCOME_IN        82728
FUEL             72853
AIRTIME          31535
SACCO_CONTRIB    13000
FAMILY_SEND       2612
DIGITAL_LOAN       658
Name: count, dtype: int64

UNIQUE DIRECTIONS:
direction
OUT    120000
IN      83386
Name: count, dtype: int64

AMOUNT STATS:
count    203386.000000
mean        556.427795
std         445.002837
min          20.000000
25%         227.630000
50%         372.535000
75%         836.295000
max        4999.920000
Name: amount, dtype: float64

RUNNING BALANCE STATS:
count    203386.000000
mean      18765.489795
std       14413.804251
min           0.000000
25%        7259.572500
50%       15168.485000
75%       26871.340000
max       92259.390000
Name: running_balance, dtype: float64

In [43]:
mpesa_clean["transaction_date"] = pd.to_datetime(mpesa_clean["transaction_date"])

In [44]:
mpesa_clean["txn_date"]      = mpesa_clean["transaction_date"].dt.date
mpesa_clean["txn_hour"]      = mpesa_clean["transaction_date"].dt.hour
mpesa_clean["txn_month"]     = mpesa_clean["transaction_date"].dt.month
mpesa_clean["txn_day"]       = mpesa_clean["transaction_date"].dt.day
mpesa_clean["txn_weekday"]   = mpesa_clean["transaction_date"].dt.weekday



mpesa_clean["is_weekend"]    = (mpesa_clean["txn_weekday"] >= 5).astype(int)
mpesa_clean["is_end_month"]  = (mpesa_clean["txn_day"] >= 28).astype(int)
mpesa_clean["is_rain_month"] = mpesa_clean["txn_month"].isin(
    [3, 4, 5, 10, 11]
).astype(int)
mpesa_clean["is_peak_hour"]  = mpesa_clean["txn_hour"].isin(
    [7, 8, 9, 17, 18, 19, 20]   # morning and evening rush hours
).astype(int)

print("✅ Date column fixed and expanded")
print()
print("New date columns added:")
print(f"  txn_date      — example: {mpesa_clean['txn_date'].iloc[0]}")
print(f"  txn_hour      — example: {mpesa_clean['txn_hour'].iloc[0]}")
print(f"  txn_month     — example: {mpesa_clean['txn_month'].iloc[0]}")
print(f"  txn_day       — example: {mpesa_clean['txn_day'].iloc[0]}")
print(f"  txn_weekday   — example: {mpesa_clean['txn_weekday'].iloc[0]} (0=Mon)")
print(f"  is_weekend    — example: {mpesa_clean['is_weekend'].iloc[0]}")
print(f"  is_end_month  — example: {mpesa_clean['is_end_month'].iloc[0]}")
print(f"  is_rain_month — example: {mpesa_clean['is_rain_month'].iloc[0]}")
print(f"  is_peak_hour  — example: {mpesa_clean['is_peak_hour'].iloc[0]}")

✅ Date column fixed and expanded

New date columns added:
  txn_date      — example: 2024-04-01
  txn_hour      — example: 7
  txn_month     — example: 4
  txn_day       — example: 1
  txn_weekday   — example: 0 (0=Mon)
  is_weekend    — example: 0
  is_end_month  — example: 0
  is_rain_month — example: 1
  is_peak_hour  — example: 1

In [45]:
print("AMOUNT COLUMN — BEFORE CLEANING")
print(f"  Total rows:        {len(mpesa_clean):,}")
print(f"  Negative amounts:  {(mpesa_clean['amount'] < 0).sum()}")
print(f"  Zero amounts:      {(mpesa_clean['amount'] == 0).sum()}")
print(f"  Min amount:        KES {mpesa_clean['amount'].min():.2f}")
print(f"  Max amount:        KES {mpesa_clean['amount'].max():.2f}")
print(f"  Mean amount:       KES {mpesa_clean['amount'].mean():.2f}")
print(f"  Median amount:     KES {mpesa_clean['amount'].median():.2f}")

# Step 1: Make all amounts positive
# Direction column (IN/OUT) already tells us the flow
# so negative sign on amount is redundant and confusing
mpesa_clean["amount"] = mpesa_clean["amount"].abs()

# Step 2: Remove zero-amount transactions
# A zero-amount transaction means nothing happened
rows_before = len(mpesa_clean)
mpesa_clean = mpesa_clean[mpesa_clean["amount"] > 0]
rows_removed = rows_before - len(mpesa_clean)
print(f"\n  Removed {rows_removed} zero-amount rows")

# Step 3: Check for extreme outliers
# A single transaction above KES 100,000 for a boda rider is suspicious
suspicious = mpesa_clean[mpesa_clean["amount"] > 100000]
print(f"\n  Transactions above KES 100,000: {len(suspicious)}")
if len(suspicious) > 0:
    print("  Suspicious transactions:")
    display(suspicious[["rider_id","txn_date","amount",
                          "direction","counterparty_type"]])

print(f"\nAMOUNT COLUMN — AFTER CLEANING")
print(f"  Min:    KES {mpesa_clean['amount'].min():.2f}")
print(f"  Max:    KES {mpesa_clean['amount'].max():.2f}")
print(f"  Mean:   KES {mpesa_clean['amount'].mean():.2f}")
print(f"  Median: KES {mpesa_clean['amount'].median():.2f}")
print(f"\n✅ Amount column cleaned")

AMOUNT COLUMN — BEFORE CLEANING
  Total rows:        203,386
  Negative amounts:  0
  Zero amounts:      0
  Min amount:        KES 20.00
  Max amount:        KES 4999.92
  Mean amount:       KES 556.43
  Median amount:     KES 372.53

  Removed 0 zero-amount rows

  Transactions above KES 100,000: 0

AMOUNT COLUMN — AFTER CLEANING
  Min:    KES 20.00
  Max:    KES 4999.92
  Mean:   KES 556.43
  Median: KES 372.53

✅ Amount column cleaned

In [46]:
print("DIRECTION COLUMN CHECK")
print()
print("Unique values found:")
print(mpesa_clean["direction"].value_counts())
print()

DIRECTION COLUMN CHECK

Unique values found:
direction
OUT    120000
IN      83386
Name: count, dtype: int64

In [47]:
valid_directions = ["IN", "OUT"]
unexpected = mpesa_clean[
    ~mpesa_clean["direction"].isin(valid_directions)
]
print(f"Unexpected direction values: {len(unexpected)}")

Unexpected direction values: 0

In [48]:
null_directions = mpesa_clean["direction"].isnull().sum()
print(f"Null direction values: {null_directions}")

if len(unexpected) == 0 and null_directions == 0:
    print("\n Direction column is clean")
else:
    # Fix unexpected values
    mpesa_clean = mpesa_clean[
        mpesa_clean["direction"].isin(valid_directions)
    ]
    print(f"\n  Removed {len(unexpected)} rows with invalid direction")

Null direction values: 0

 Direction column is clean

In [49]:
mpesa_clean["is_inflow"] = (mpesa_clean["direction"] == "IN").astype(int)

print(f"\nInflow transactions:  {mpesa_clean['is_inflow'].sum():,}")
print(f"Outflow transactions: {(mpesa_clean['is_inflow']==0).sum():,}")

Inflow transactions:  83,386
Outflow transactions: 120,000

In [50]:
print("COUNTERPARTY TYPE — VALIDATION")
print()

# These are the only valid types we defined in Step 2
VALID_TYPES = [
    "INCOME_IN",
    "FUEL",
    "SACCO_CONTRIB",
    "FAMILY_SEND",
    "DIGITAL_LOAN",
    "AIRTIME",
    "UNCLASSIFIED"
]

print("Types found in data:")
type_counts = mpesa_clean["counterparty_type"].value_counts()
for txn_type, count in type_counts.items():
    pct = count / len(mpesa_clean) * 100
    is_valid = "✅" if txn_type in VALID_TYPES else "⚠️ UNEXPECTED"
    print(f"  {is_valid} {txn_type:<20} {count:>7,} rows  ({pct:.1f}%)")

# Tag any unknown types as UNCLASSIFIED
mpesa_clean.loc[
    ~mpesa_clean["counterparty_type"].isin(VALID_TYPES),
    "counterparty_type"
] = "UNCLASSIFIED"

print(f"\n✅ Counterparty types validated")
print(f"   Any unknown types tagged as UNCLASSIFIED")

COUNTERPARTY TYPE — VALIDATION

Types found in data:
  ✅ INCOME_IN             82,728 rows  (40.7%)
  ✅ FUEL                  72,853 rows  (35.8%)
  ✅ AIRTIME               31,535 rows  (15.5%)
  ✅ SACCO_CONTRIB         13,000 rows  (6.4%)
  ✅ FAMILY_SEND            2,612 rows  (1.3%)
  ✅ DIGITAL_LOAN             658 rows  (0.3%)

✅ Counterparty types validated
   Any unknown types tagged as UNCLASSIFIED

In [51]:
print("RUNNING BALANCE — CHECK")
print()
print(f"Min balance:    KES {mpesa_clean['running_balance'].min():.2f}")
print(f"Max balance:    KES {mpesa_clean['running_balance'].max():.2f}")
print(f"Mean balance:   KES {mpesa_clean['running_balance'].mean():.2f}")
print(f"Null balances:  {mpesa_clean['running_balance'].isnull().sum()}")

# Count negative balances — these are Fuliza situations
negative_balances = (mpesa_clean["running_balance"] < 0).sum()
very_negative     = (mpesa_clean["running_balance"] < -5000).sum()

print(f"\nNegative balance rows:       {negative_balances}")
print(f"Very negative (<-5000) rows: {very_negative}")

# Very negative balances suggest data error — cap them
if very_negative > 0:
    print(f"\n⚠️  Capping balances below -5000 to -5000")
    mpesa_clean["running_balance"] = mpesa_clean["running_balance"].clip(lower=-5000)

# Fill any null balances with 0
mpesa_clean["running_balance"] = mpesa_clean["running_balance"].fillna(0)

print(f"\n✅ Running balance cleaned")
print(f"   Min balance after cleaning: KES {mpesa_clean['running_balance'].min():.2f}")

RUNNING BALANCE — CHECK

Min balance:    KES 0.00
Max balance:    KES 92259.39
Mean balance:   KES 18765.49
Null balances:  0

Negative balance rows:       0
Very negative (<-5000) rows: 0

✅ Running balance cleaned
   Min balance after cleaning: KES 0.00

In [52]:
print("=" * 55)
print("  M-PESA TABLE — FINAL CLEANED STATE")
print("=" * 55)
print(f"\n  Total rows:        {len(mpesa_clean):,}")
print(f"  Total riders:      {mpesa_clean['rider_id'].nunique():,}")
print(f"  Date range:        {mpesa_clean['txn_date'].min()} "
      f"to {mpesa_clean['txn_date'].max()}")
print(f"  Missing values:    {mpesa_clean.isnull().sum().sum()}")
print()
print("  FINAL COLUMNS:")
for col in mpesa_clean.columns:
    dtype = mpesa_clean[col].dtype
    nulls = mpesa_clean[col].isnull().sum()
    print(f"  ✅  {col:<30} dtype={str(dtype):<10} nulls={nulls}")

print()
print("  TRANSACTION TYPE BREAKDOWN:")
for txn_type, count in mpesa_clean["counterparty_type"].value_counts().items():
    bar = "█" * int(count / 1000)
    print(f"  {txn_type:<20} {count:>7,}  {bar}")

print()

# Quick sanity check on income transactions
income = mpesa_clean[mpesa_clean["counterparty_type"] == "INCOME_IN"]
print(f"  Avg daily income transaction: KES {income['amount'].mean():.0f}")
print(f"  Avg fuel transaction:         "
      f"KES {mpesa_clean[mpesa_clean['counterparty_type']=='FUEL']['amount'].mean():.0f}")

print()
print("✅ M-Pesa table is clean and ready for feature engineering")
print()

# Save the cleaned version
mpesa_clean.to_csv("mpesa_clean.csv", index=False)
print("💾 Saved as mpesa_clean.csv")

=======================================================
  M-PESA TABLE — FINAL CLEANED STATE
=======================================================

  Total rows:        203,386
  Total riders:      1,000
  Date range:        2024-04-01 to 2024-06-29
  Missing values:    0

  FINAL COLUMNS:
  ✅  rider_id                       dtype=object     nulls=0
  ✅  transaction_date               dtype=datetime64[ns] nulls=0
  ✅  amount                         dtype=float64    nulls=0
  ✅  direction                      dtype=object     nulls=0
  ✅  counterparty_name              dtype=object     nulls=0
  ✅  counterparty_type              dtype=object     nulls=0
  ✅  running_balance                dtype=float64    nulls=0
  ✅  txn_date                       dtype=object     nulls=0
  ✅  txn_month                      dtype=int32      nulls=0
  ✅  txn_day                        dtype=int32      nulls=0
  ✅  txn_weekday                    dtype=int32      nulls=0
  ✅  is_weekend                     dtype=int64      nulls=0
  ✅  is_end_month                   dtype=int64      nulls=0
  ✅  is_rain_month                  dtype=int64      nulls=0
  ✅  txn_hour                       dtype=int32      nulls=0
  ✅  is_peak_hour                   dtype=int64      nulls=0
  ✅  is_inflow                      dtype=int64      nulls=0

  TRANSACTION TYPE BREAKDOWN:
  INCOME_IN             82,728  ██████████████████████████████████████████████████████████████████████████████████
  FUEL                  72,853  ████████████████████████████████████████████████████████████████████████
  AIRTIME               31,535  ███████████████████████████████
  SACCO_CONTRIB         13,000  █████████████
  FAMILY_SEND            2,612  ██
  DIGITAL_LOAN             658

  Avg daily income transaction: KES 900
  Avg fuel transaction:         KES 271

✅ M-Pesa table is clean and ready for feature engineering

💾 Saved as mpesa_clean.csv

In [53]:
mpesa_clean.head()

,rider_id,transaction_date,amount,direction,counterparty_name,counterparty_type,running_balance,txn_date,txn_month,txn_day,txn_weekday,is_weekend,is_end_month,is_rain_month,txn_hour,is_peak_hour,is_inflow
0,RDR-00001,2024-04-01 07:28:00,676.15,IN,App Payout,INCOME_IN,3382.55,2024-04-01,4,1,0,0,0,1,7,1,1
1,RDR-00001,2024-04-01 06:05:00,281.43,OUT,Rubis Energy,FUEL,3101.12,2024-04-01,4,1,0,0,0,1,6,0,0
2,RDR-00001,2024-04-01 10:00:00,713.47,OUT,Eastside Riders SACCO,SACCO_CONTRIB,2387.65,2024-04-01,4,1,0,0,0,1,10,0,0
3,RDR-00001,2024-04-01 08:00:00,50.00,OUT,Safaricom Airtime,AIRTIME,2337.65,2024-04-01,4,1,0,0,0,1,8,1,0
4,RDR-00001,2024-04-02 07:42:00,751.28,IN,App Payout,INCOME_IN,3088.93,2024-04-02,4,2,1,0,0,1,7,1,1

In [54]:
loans.head()

,loan_id,rider_id,lender_name,lender_type,loan_amount,loan_purpose,disbursement_date,due_date,completion_date,days_early_late,default_flag,restructured_flag,outstanding_balance,repayment_frequency
0,LN-000001,RDR-00003,Tala Kenya,Digital,4496.31,Bike Repair,2023-05-07,2023-07-06,2023-07-15,9,False,False,0.00,Weekly
1,LN-000002,RDR-00003,Branch International,Digital,4191.17,Business Expansion,2023-05-07,2023-07-06,2023-07-04,-2,False,False,0.00,Monthly
2,LN-000003,RDR-00003,Juhudi Kilimo,MFI,27601.41,Bike Upgrade,2023-05-07,2023-08-05,2023-09-06,32,False,False,0.00,Weekly
3,LN-000004,RDR-00003,Musoni Kenya,MFI,61678.14,Bike Repair,2023-08-05,2024-08-04,NaN,0,False,False,24751.76,Monthly
4,LN-000005,RDR-00005,Juhudi Kilimo,MFI,19032.38,Emergency Medical,2023-04-07,2024-04-06,2024-04-02,-4,False,False,0.00,Daily

In [55]:
loans["is_completed"] = loans["completion_date"].notna().astype(int)

In [56]:
loans["is_completed"] = loans["completion_date"].notna().astype(int)

In [57]:
loans["default_flag"] = loans["default_flag"].astype(int)

In [58]:
loans["restructured_flag"] = loans["restructured_flag"].astype(int)

In [59]:
loans["days_early_late"] = loans["days_early_late"].fillna(0)

In [60]:
loans.head()

,loan_id,rider_id,lender_name,lender_type,loan_amount,loan_purpose,disbursement_date,due_date,completion_date,days_early_late,default_flag,restructured_flag,outstanding_balance,repayment_frequency,is_completed
0,LN-000001,RDR-00003,Tala Kenya,Digital,4496.31,Bike Repair,2023-05-07,2023-07-06,2023-07-15,9,0,0,0.00,Weekly,1
1,LN-000002,RDR-00003,Branch International,Digital,4191.17,Business Expansion,2023-05-07,2023-07-06,2023-07-04,-2,0,0,0.00,Monthly,1
2,LN-000003,RDR-00003,Juhudi Kilimo,MFI,27601.41,Bike Upgrade,2023-05-07,2023-08-05,2023-09-06,32,0,0,0.00,Weekly,1
3,LN-000004,RDR-00003,Musoni Kenya,MFI,61678.14,Bike Repair,2023-08-05,2024-08-04,NaN,0,0,0,24751.76,Monthly,0
4,LN-000005,RDR-00005,Juhudi Kilimo,MFI,19032.38,Emergency Medical,2023-04-07,2024-04-06,2024-04-02,-4,0,0,0.00,Daily,1

In [61]:
LOANS_DROP_COLUMNS = [
    "loan_id",
    "lender_name",
    "loan_purpose",
    "disbursement_date",
    "due_date",
    "completion_date",
]
loans_clean = loans.drop(columns=LOANS_DROP_COLUMNS)

In [62]:
loans_clean.head()

,rider_id,lender_type,loan_amount,days_early_late,default_flag,restructured_flag,outstanding_balance,repayment_frequency,is_completed
0,RDR-00003,Digital,4496.31,9,0,0,0.00,Weekly,1
1,RDR-00003,Digital,4191.17,-2,0,0,0.00,Monthly,1
2,RDR-00003,MFI,27601.41,32,0,0,0.00,Weekly,1
3,RDR-00003,MFI,61678.14,0,0,0,24751.76,Monthly,0
4,RDR-00005,MFI,19032.38,-4,0,0,0.00,Daily,1

In [63]:

lender_type_map = {
    "SACCO":   1,
    "MFI":     2,
    "Digital": 3,
}
loans_clean["lender_type_code"] = loans_clean["lender_type"].map(lender_type_map)
loans_clean = loans_clean.drop(columns=["lender_type"])

# Encode repayment frequency
# Daily = 2 (best match for boda income pattern)
# Weekly = 1
# Monthly = 0 (hardest for boda riders to manage)
freq_map = {
    "Daily":   2,
    "Weekly":  1,
    "Monthly": 0,
}
loans_clean["repayment_freq_code"] = loans_clean["repayment_frequency"].map(freq_map)
loans_clean = loans_clean.drop(columns=["repayment_frequency"])

print("✅ Text columns encoded")
print()
print("FINAL LOANS TABLE:")
for col in loans_clean.columns:
    print(f"  ✅ {col:<25} dtype={str(loans_clean[col].dtype)}")

print()
display(loans_clean.head(3))

✅ Text columns encoded

FINAL LOANS TABLE:
  ✅ rider_id                  dtype=object
  ✅ loan_amount               dtype=float64
  ✅ days_early_late           dtype=int64
  ✅ default_flag              dtype=int64
  ✅ restructured_flag         dtype=int64
  ✅ outstanding_balance       dtype=float64
  ✅ is_completed              dtype=int64
  ✅ lender_type_code          dtype=int64
  ✅ repayment_freq_code       dtype=int64

,rider_id,loan_amount,days_early_late,default_flag,restructured_flag,outstanding_balance,is_completed,lender_type_code,repayment_freq_code
0,RDR-00003,4496.31,9,0,0,0.0,1,3,1
1,RDR-00003,4191.17,-2,0,0,0.0,1,3,0
2,RDR-00003,27601.41,32,0,0,0.0,1,2,1

In [64]:
loans_clean["lender_type"].value_counts()

KeyError: 'lender_type'

In [65]:
lender_type_map = {
    "SACCO":   1,
    "MFI":     2,
    "Digital": 3,
}
loans_clean["lender_type_code"] = loans_clean["lender_type"].map(lender_type_map)
loans_clean = loans_clean.drop(columns=["lender_type"])

KeyError: 'lender_type'

In [66]:
freq_map = {
    "Daily":   2,
    "Weekly":  1,
    "Monthly": 0,
}
loans_clean["repayment_freq_code"] = loans_clean["repayment_frequency"].map(freq_map)
loans_clean = loans_clean.drop(columns=["repayment_frequency"])

KeyError: 'repayment_frequency'

In [67]:
loans_clean.head()

,rider_id,loan_amount,days_early_late,default_flag,restructured_flag,outstanding_balance,is_completed,lender_type_code,repayment_freq_code
0,RDR-00003,4496.31,9,0,0,0.00,1,3,1
1,RDR-00003,4191.17,-2,0,0,0.00,1,3,0
2,RDR-00003,27601.41,32,0,0,0.00,1,2,1
3,RDR-00003,61678.14,0,0,0,24751.76,0,2,0
4,RDR-00005,19032.38,-4,0,0,0.00,1,2,2

In [68]:
sacco.head()

,record_id,rider_id,sacco_id,month_year,months_as_member,monthly_contribution,contribution_made,contribution_on_time,days_late,cumulative_savings,shares_owned,active_loan_balance,loan_repayment_status,guarantor_count
0,SAC-RDR-00001-202301,RDR-00001,SAC-002,2023-01-01,1,1591.67,True,True,0,1591.67,1,0.0,Clean,1
1,SAC-RDR-00001-202302,RDR-00001,SAC-002,2023-02-01,2,1591.67,True,True,0,3183.33,1,0.0,Clean,0
2,SAC-RDR-00001-202303,RDR-00001,SAC-002,2023-03-01,3,1591.67,True,True,0,4775.00,1,0.0,Clean,0
3,SAC-RDR-00001-202304,RDR-00001,SAC-002,2023-04-01,4,1591.67,True,True,0,6366.66,1,0.0,Clean,3
4,SAC-RDR-00001-202305,RDR-00001,SAC-002,2023-05-01,5,1591.67,False,True,0,6366.66,1,0.0,Clean,1

In [69]:
sacco["contribution_made"]    = sacco["contribution_made"].astype(int)
sacco["contribution_on_time"] = sacco["contribution_on_time"].astype(int)

# Days late: fill NaN with 0 (if they didn't pay, days_late is irrelevant)
sacco["days_late"] = sacco["days_late"].fillna(0)

In [70]:
sacco["loan_repayment_status"].value_counts()

loan_repayment_status
Clean    5227
Name: count, dtype: int64

In [71]:
SACCO_DROP_COLS = [
    "record_id",            
    "sacco_id",            
    "month_year",          
    "loan_repayment_status" 
]

sacco_clean = sacco.drop(columns=SACCO_DROP_COLS)

In [72]:
# loan_repayment_status is text: "Clean", "Late", "Defaulted"
# We encode it as a number before dropping the text column

print("Unique loan_repayment_status values:")
print(sacco["loan_repayment_status"].value_counts())

repayment_status_map = {
    "Clean":     2,   # best — no issues
    "Late":      1,   # mild concern
    "Defaulted": 0,   # serious concern
}

sacco_clean["repayment_status_code"] = (
    sacco["loan_repayment_status"]
    .map(repayment_status_map)
    .fillna(2)   # if unknown assume clean
)

print("\n✅ loan_repayment_status encoded as repayment_status_code")
print(sacco_clean["repayment_status_code"].value_counts())

Unique loan_repayment_status values:
loan_repayment_status
Clean    5227
Name: count, dtype: int64

✅ loan_repayment_status encoded as repayment_status_code
repayment_status_code
2    5227
Name: count, dtype: int64

In [73]:
# Make sure boolean columns are proper integers
sacco_clean["contribution_made"]    = sacco_clean["contribution_made"].astype(int)
sacco_clean["contribution_on_time"] = sacco_clean["contribution_on_time"].astype(int)

# days_late should be 0 when contribution was not made
# because days_late is irrelevant if they did not contribute at all
sacco_clean["days_late"] = sacco_clean["days_late"].fillna(0)

# active_loan_balance should be 0 if no active loan
sacco_clean["active_loan_balance"] = sacco_clean["active_loan_balance"].fillna(0)

print("✅ Boolean columns fixed")
print()
print("contribution_made values:")
print(sacco_clean["contribution_made"].value_counts())
print()
print("contribution_on_time values:")
print(sacco_clean["contribution_on_time"].value_counts())

✅ Boolean columns fixed

contribution_made values:
contribution_made
1    4352
0     875
Name: count, dtype: int64

contribution_on_time values:
contribution_on_time
1    4607
0     620
Name: count, dtype: int64

In [74]:
sacco_clean.head()

,rider_id,months_as_member,monthly_contribution,contribution_made,contribution_on_time,days_late,cumulative_savings,shares_owned,active_loan_balance,guarantor_count,repayment_status_code
0,RDR-00001,1,1591.67,1,1,0,1591.67,1,0.0,1,2
1,RDR-00001,2,1591.67,1,1,0,3183.33,1,0.0,0,2
2,RDR-00001,3,1591.67,1,1,0,4775.00,1,0.0,0,2
3,RDR-00001,4,1591.67,1,1,0,6366.66,1,0.0,3,2
4,RDR-00001,5,1591.67,0,1,0,6366.66,1,0.0,1,2

In [75]:
apps.head()

,application_id,rider_id,application_date,requested_amount,requested_term_days,loan_purpose,score_date,final_score,risk_category,pd_score,recommended_amount,recommended_term_days,decision,actual_default,risk_score_debug
0,APP-2024-RDR-00001,RDR-00001,2024-06-30,10000,90,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,6.36
1,APP-2024-RDR-00002,RDR-00002,2024-06-30,15000,60,Bike Repair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,23.69
2,APP-2024-RDR-00003,RDR-00003,2024-06-30,20000,180,Working Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,10.00
3,APP-2024-RDR-00004,RDR-00004,2024-06-30,20000,120,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,26.25
4,APP-2024-RDR-00005,RDR-00005,2024-06-30,50000,30,Emergency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1.00

In [76]:
TRIPS_DROP_COLS = [
    "trip_record_id",    
    "week_start_date",   
]

In [77]:
trips_clean = trips.drop(columns=TRIPS_DROP_COLS)

In [78]:
trips_clean.head()

,rider_id,total_trips,active_days,gross_earnings_week,platform_rating,cancellation_rate,peak_hour_trips,longest_inactive_streak
0,RDR-00001,45,6,7879.83,4.3,0.099,17,0
1,RDR-00001,56,6,8916.24,4.4,0.049,22,0
2,RDR-00001,42,5,5699.78,4.4,0.042,15,1
3,RDR-00001,40,5,4893.77,4.3,0.065,19,1
4,RDR-00001,47,7,5853.08,4.4,0.102,18,0

In [80]:
trips_clean["longest_inactive_streak"].value_counts()

longest_inactive_streak
0    11304
1     6958
2     3441
3     1125
Name: count, dtype: int64

In [81]:
import os

files = [
    "riders_clean.csv",
    "mpesa_clean.csv",
    "loans_clean.csv",
    "sacco_clean.csv",
    "trips_clean.csv",
    "apps_clean.csv",
]

print("CHECKING CLEAN FILES EXIST")
print()
for f in files:
    exists = os.path.exists(f)
    size   = os.path.getsize(f) if exists else 0
    status = "✅" if exists else "❌ MISSING"
    print(f"  {status}  {f:<25}  {size/1024:.0f} KB")

CHECKING CLEAN FILES EXIST

  ✅  riders_clean.csv           28 KB
  ✅  mpesa_clean.csv            20615 KB
  ✅  loans_clean.csv            50 KB
  ✅  sacco_clean.csv            235 KB
  ✅  trips_clean.csv            862 KB
  ✅  apps_clean.csv             24 KB

In [82]:
apps.head()

,application_id,rider_id,application_date,requested_amount,requested_term_days,loan_purpose,score_date,final_score,risk_category,pd_score,recommended_amount,recommended_term_days,decision,actual_default,risk_score_debug
0,APP-2024-RDR-00001,RDR-00001,2024-06-30,10000,90,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,6.36
1,APP-2024-RDR-00002,RDR-00002,2024-06-30,15000,60,Bike Repair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,23.69
2,APP-2024-RDR-00003,RDR-00003,2024-06-30,20000,180,Working Capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,10.00
3,APP-2024-RDR-00004,RDR-00004,2024-06-30,20000,120,Bike Upgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,26.25
4,APP-2024-RDR-00005,RDR-00005,2024-06-30,50000,30,Emergency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1.00

In [83]:
PIPELINE_OUTPUT_COLS = [
    "score_date",
    "final_score",
    "risk_category",
    "pd_score",
    "recommended_amount",
    "recommended_term_days",
    "decision",
]

# These are identifiers or zero-variance columns
IDENTIFIER_COLS = [
    "application_id",
    "application_date",
]

ALL_DROP_COLS = PIPELINE_OUTPUT_COLS + IDENTIFIER_COLS

apps_clean = apps.drop(columns=ALL_DROP_COLS)

In [84]:
apps_clean.head()

,rider_id,requested_amount,requested_term_days,loan_purpose,actual_default,risk_score_debug
0,RDR-00001,10000,90,Bike Upgrade,False,6.36
1,RDR-00002,15000,60,Bike Repair,False,23.69
2,RDR-00003,20000,180,Working Capital,False,10.00
3,RDR-00004,20000,120,Bike Upgrade,False,26.25
4,RDR-00005,50000,30,Emergency,False,1.00

In [85]:
# loan_purpose is text — encode as number
print("Unique loan purposes:")
print(apps_clean["loan_purpose"].value_counts())

purpose_map = {
    "Bike Repair":     1,
    "Working Capital": 2,
    "Bike Upgrade":    3,
    "Emergency":       4,
    "Bike Purchase":   5,
}

apps_clean["loan_purpose_code"] = (
    apps_clean["loan_purpose"]
    .map(purpose_map)
    .fillna(3)   # unknown purpose treated as Bike Upgrade (middle risk)
)

# Drop the text version
apps_clean = apps_clean.drop(columns=["loan_purpose"])

print("\n✅ loan_purpose encoded as loan_purpose_code")
print(apps_clean["loan_purpose_code"].value_counts())

Unique loan purposes:
loan_purpose
Bike Upgrade       219
Bike Purchase      210
Bike Repair        198
Working Capital    196
Emergency          177
Name: count, dtype: int64

✅ loan_purpose encoded as loan_purpose_code
loan_purpose_code
3    219
5    210
1    198
2    196
4    177
Name: count, dtype: int64

In [86]:
apps_clean.head()

,rider_id,requested_amount,requested_term_days,actual_default,risk_score_debug,loan_purpose_code
0,RDR-00001,10000,90,False,6.36,3
1,RDR-00002,15000,60,False,23.69,1
2,RDR-00003,20000,180,False,10.00,2
3,RDR-00004,20000,120,False,26.25,3
4,RDR-00005,50000,30,False,1.00,4

In [87]:
# actual_default must be a clean integer — 0 or 1
# Check what it currently looks like
print("actual_default current values:")
print(apps_clean["actual_default"].value_counts())
print(f"dtype: {apps_clean['actual_default'].dtype}")

# Convert True/False to 1/0
apps_clean["actual_default"] = apps_clean["actual_default"].astype(int)

print("\nAfter conversion:")
print(apps_clean["actual_default"].value_counts())
print(f"dtype: {apps_clean['actual_default'].dtype}")
print()
print(f"Default rate: {apps_clean['actual_default'].mean():.1%}")
print(f"Defaulters:   {apps_clean['actual_default'].sum()}")
print(f"Non-defaulters: {(apps_clean['actual_default']==0).sum()}")

actual_default current values:
actual_default
False    704
True     296
Name: count, dtype: int64
dtype: bool

After conversion:
actual_default
0    704
1    296
Name: count, dtype: int64
dtype: int64

Default rate: 29.6%
Defaulters:   296
Non-defaulters: 704

In [88]:
print("APPLICATIONS TABLE — SANITY CHECK")
print()
print(f"  Total applications:   {len(apps_clean):,}")
print(f"  Unique riders:        {apps_clean['rider_id'].nunique():,}")
print(f"  Missing values:       {apps_clean.isnull().sum().sum()}")
print(f"  Default rate:         {apps_clean['actual_default'].mean():.1%}")
print()
print(f"  Requested amounts:")
print(f"    Min:    KES {apps_clean['requested_amount'].min():,.0f}")
print(f"    Max:    KES {apps_clean['requested_amount'].max():,.0f}")
print(f"    Mean:   KES {apps_clean['requested_amount'].mean():,.0f}")
print()
print(f"  Requested terms:")
print(f"    Min:    {apps_clean['requested_term_days'].min()} days")
print(f"    Max:    {apps_clean['requested_term_days'].max()} days")
print(f"    Mean:   {apps_clean['requested_term_days'].mean():.0f} days")
print()
print("  FINAL COLUMNS:")
for col in apps_clean.columns:
    print(f"  ✅ {col:<25} dtype={str(apps_clean[col].dtype)}")

# One row per rider — confirm
print()
print(f"  Rows per rider: exactly 1 — {apps_clean['rider_id'].nunique() == len(apps_clean)}")

# Save
apps_clean.to_csv("apps_clean.csv", index=False)
print()
print("  ✅ Applications table clean and ready")
print("  💾 Saved as apps_clean.csv")

APPLICATIONS TABLE — SANITY CHECK

  Total applications:   1,000
  Unique riders:        1,000
  Missing values:       0
  Default rate:         29.6%

  Requested amounts:
    Min:    KES 5,000
    Max:    KES 50,000
    Mean:   KES 19,125

  Requested terms:
    Min:    30 days
    Max:    180 days
    Mean:   94 days

  FINAL COLUMNS:
  ✅ rider_id                  dtype=object
  ✅ requested_amount          dtype=int64
  ✅ requested_term_days       dtype=int64
  ✅ actual_default            dtype=int64
  ✅ risk_score_debug          dtype=float64
  ✅ loan_purpose_code         dtype=int64

  Rows per rider: exactly 1 — True

  ✅ Applications table clean and ready
  💾 Saved as apps_clean.csv

In [89]:
apps_clean.head()

,rider_id,requested_amount,requested_term_days,actual_default,risk_score_debug,loan_purpose_code
0,RDR-00001,10000,90,0,6.36,3
1,RDR-00002,15000,60,0,23.69,1
2,RDR-00003,20000,180,0,10.00,2
3,RDR-00004,20000,120,0,26.25,3
4,RDR-00005,50000,30,0,1.00,4

In [90]:
print("DATAFRAMES IN MEMORY — STATUS CHECK")
print()

dataframes = {
    "riders_clean": riders_clean,
    "mpesa_clean":  mpesa_clean,
    "loans_clean":  loans_clean,
    "sacco_clean":  sacco_clean,
    "trips_clean":  trips_clean,
    "apps_clean":   apps_clean,
}

for name, df in dataframes.items():
    print(f"  ✅ {name:<20} "
          f"rows={len(df):>7,}  "
          f"cols={df.shape[1]:>3}  "
          f"missing={df.isnull().sum().sum()}")

DATAFRAMES IN MEMORY — STATUS CHECK

  ✅ riders_clean         rows=  1,000  cols=  8  missing=0
  ✅ mpesa_clean          rows=203,386  cols= 17  missing=0
  ✅ loans_clean          rows=  1,390  cols=  9  missing=0
  ✅ sacco_clean          rows=  5,227  cols= 11  missing=0
  ✅ trips_clean          rows= 22,828  cols=  8  missing=0
  ✅ apps_clean           rows=  1,000  cols=  6  missing=0

In [91]:
riders_clean.to_csv("riders_clean.csv", index=False)
mpesa_clean.to_csv("mpesa_clean.csv", index=False)
loans_clean.to_csv("loans_clean.csv", index=False)
sacco_clean.to_csv("sacco_clean.csv", index=False)
trips_clean.to_csv("trips_clean.csv", index=False)
apps_clean.to_csv("apps_clean.csv", index=False)

print("✅ All 6 DataFrames saved as CSV files")

✅ All 6 DataFrames saved as CSV files